/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegularizeRouteImport } from './routes/regularize'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminPeopleRouteImport } from './routes/admin/people'
import { Route as AdminPolicyRouteImport } from './routes/admin/policy'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminSessionsIdRouteImport } from './routes/admin/sessions.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularizeRoute = RegularizeRouteImport.update({
  id: '/regularize',
  path: '/regularize',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyRoute = AdminPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsIdRoute = AdminSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSessionsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/regularize': typeof RegularizeRoute
  '/team': typeof TeamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/sessions/$id': typeof AdminSessionsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/regularize': typeof RegularizeRoute
  '/team': typeof TeamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/sessions/$id': typeof AdminSessionsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/regularize': typeof RegularizeRoute
  '/team': typeof TeamRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/sessions/$id': typeof AdminSessionsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/help'
    | '/history'
    | '/leave'
    | '/login'
    | '/more'
    | '/privacy'
    | '/profile'
    | '/regularize'
    | '/team'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/locations'
    | '/admin/people'
    | '/admin/policy'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/'
    | '/admin/sessions/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/history'
    | '/leave'
    | '/login'
    | '/more'
    | '/privacy'
    | '/profile'
    | '/regularize'
    | '/team'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/locations'
    | '/admin/people'
    | '/admin/policy'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin'
    | '/admin/sessions/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/help'
    | '/history'
    | '/leave'
    | '/login'
    | '/more'
    | '/privacy'
    | '/profile'
    | '/regularize'
    | '/team'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/locations'
    | '/admin/people'
    | '/admin/policy'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/'
    | '/admin/sessions/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegularizeRoute: typeof RegularizeRoute
  TeamRoute: typeof TeamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regularize': {
      id: '/regularize'
      path: '/regularize'
      fullPath: '/regularize'
      preLoaderRoute: typeof RegularizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy': {
      id: '/admin/policy'
      path: '/policy'
      fullPath: '/admin/policy'
      preLoaderRoute: typeof AdminPolicyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/$id': {
      id: '/admin/sessions/$id'
      path: '/$id'
      fullPath: '/admin/sessions/$id'
      preLoaderRoute: typeof AdminSessionsIdRouteImport
      parentRoute: typeof AdminSessionsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminSessionsRouteChildren {
  AdminSessionsIdRoute: typeof AdminSessionsIdRoute
}

const AdminSessionsRouteChildren: AdminSessionsRouteChildren = {
  AdminSessionsIdRoute: AdminSessionsIdRoute,
}

const AdminSessionsRouteWithChildren = AdminSessionsRoute._addFileChildren(
  AdminSessionsRouteChildren,
)

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminPolicyRoute: typeof AdminPolicyRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSessionsRoute: typeof AdminSessionsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminPolicyRoute: AdminPolicyRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSessionsRoute: AdminSessionsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegularizeRoute: RegularizeRoute,
  TeamRoute: TeamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
